# Torch Tutorial Start!

    Part 1: Tensors

In [1]:
import torch

In [2]:
a=torch.ones(2,3,3)
print(a)

aa,b,c = a.size()
print(aa)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
2


The tensor in the torch is similar as the numpy array. A 3-D tensor means 3 channels or layers 2-D matrix.

In [3]:
x=torch.tensor([6,3], dtype=torch.double)
print(x)
xx=x.new_ones(5,3)
print(xx)
x = torch.randn_like(xx, dtype=torch.float)    # override dtype!
print(x)  

tensor([6., 3.], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2344, -0.0669,  0.5242],
        [-0.6582, -1.1356,  0.9726],
        [ 0.8391,  1.2520,  0.4337],
        [ 0.8062, -0.3926, -0.4424],
        [ 1.2868,  1.2400,  0.1666]])


可以看到，new_ones函数复用了x的dtype属性，randn_like函数复用了x的shape同时通过手动指定数据类型覆盖了原有的dtype属性

In [4]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

arrange函数参数有三个，分别是范围的起始值、范围的结束值和步长

Part2: Operations

In [5]:
'''加减乘除'''
y = torch.rand(5,3)
z1 = xx+y
print(z1)

tensor([[1.6739, 1.5701, 1.8355],
        [1.7760, 1.2547, 1.9762],
        [1.9728, 1.1476, 1.1055],
        [1.5647, 1.3715, 1.4527],
        [1.2396, 1.3980, 1.2273]], dtype=torch.float64)


In [6]:
z2 = torch.add(z1,y)
print(z2)

tensor([[2.3478, 2.1403, 2.6711],
        [2.5520, 1.5093, 2.9525],
        [2.9455, 1.2952, 1.2111],
        [2.1295, 1.7431, 1.9054],
        [1.4792, 1.7959, 1.4545]], dtype=torch.float64)


In [7]:
z3 = torch.empty(5,3)
print(z3)
torch.add(z1,z2, out=z3)
print(z3)

tensor([[-2.1245e-33,  3.0719e-41, -2.1246e-33],
        [ 3.0719e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -2.1245e-33],
        [ 3.0719e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[4.0218, 3.7104, 4.5066],
        [4.3279, 2.7640, 4.9287],
        [4.9183, 2.4428, 2.3166],
        [3.6942, 3.1146, 3.3581],
        [2.7188, 3.1939, 2.6818]])


In [8]:
z2.add_(z1)
print(z2)

tensor([[4.0218, 3.7104, 4.5066],
        [4.3279, 2.7640, 4.9287],
        [4.9183, 2.4428, 2.3166],
        [3.6942, 3.1146, 3.3581],
        [2.7188, 3.1939, 2.6818]], dtype=torch.float64)


In [9]:
c=torch.sub(z1,z2)
print(c)
d=torch.mul(z1,z2)
print(d)
e=torch.div(z1,z2)
print(e)

tensor([[-2.3478, -2.1403, -2.6711],
        [-2.5520, -1.5093, -2.9525],
        [-2.9455, -1.2952, -1.2111],
        [-2.1295, -1.7431, -1.9054],
        [-1.4792, -1.7959, -1.4545]], dtype=torch.float64)
tensor([[6.7321, 5.8260, 8.2721],
        [7.6864, 3.4679, 9.7404],
        [9.7025, 2.8034, 2.5611],
        [5.7805, 4.2719, 4.8782],
        [3.3702, 4.4650, 3.2913]], dtype=torch.float64)
tensor([[0.4162, 0.4232, 0.4073],
        [0.4104, 0.4539, 0.4010],
        [0.4011, 0.4698, 0.4772],
        [0.4236, 0.4404, 0.4326],
        [0.4559, 0.4377, 0.4576]], dtype=torch.float64)


In [10]:
'''tensor for matrix multiplication'''
a = torch.tensor([[-1,3,4],[2,2,2]])
print(a)
b = a.t()
c = torch.mm(a,b)
print(c)
print(a.abs())

tensor([[-1,  3,  4],
        [ 2,  2,  2]])
tensor([[26, 12],
        [12, 12]])
tensor([[1, 3, 4],
        [2, 2, 2]])


In [11]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

True
tensor([[ 1.2344,  0.9331,  1.5242],
        [ 0.3418, -0.1356,  1.9726],
        [ 1.8391,  2.2520,  1.4337],
        [ 1.8062,  0.6074,  0.5576],
        [ 2.2868,  2.2400,  1.1666]], device='cuda:0')
tensor([[ 1.2344,  0.9331,  1.5242],
        [ 0.3418, -0.1356,  1.9726],
        [ 1.8391,  2.2520,  1.4337],
        [ 1.8062,  0.6074,  0.5576],
        [ 2.2868,  2.2400,  1.1666]], dtype=torch.float64)


Part3: Auto Gradient!!